In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/workspaces/uniswap-v3-crawler/data/aggregate/aggregated_1749964745.csv.gz", compression="gzip")
df.head()

/tmp/ipykernel_52452/294404120.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/workspaces/uniswap-v3-crawler/data/aggregate/aggregated_1749964745.csv.gz", compression="gzip")

,coin_id,algorithm_error,preprocessing_time,algorithm_execution_time,block_number,algorithm_name,graph_nodes,graph_edges,graph_creation_time,source_selection_mode,total_time_seconds,source_file,top_coins
0,0x0000000000000000000000000000000000000000,"('O', '0x0000000000000000000000000000000000000...",0.0,1.749918e+09,22686000.0,mmbf,100.0,287.0,0.73758,selected,1.749918e+09,result_mmbf_22686000_100_selected.csv,100
1,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,0.0,2.204990e-01,22686000.0,mmbf,100.0,287.0,0.73758,selected,1.749918e+09,result_mmbf_22686000_100_selected.csv,100
2,0x2260fac5e5542a773aa44fbcfedf7c193bc2c599,NaN,0.0,2.040131e-01,22686000.0,mmbf,100.0,287.0,0.73758,selected,1.749918e+09,result_mmbf_22686000_100_selected.csv,100
3,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,NaN,0.0,2.081912e-01,22686000.0,mmbf,100.0,287.0,0.73758,selected,1.749918e+09,result_mmbf_22686000_100_selected.csv,100
4,0xdac17f958d2ee523a2206206994597c13d831ec7,NaN,0.0,2.326393e-01,22686000.0,mmbf,100.0,287.0,0.73758,selected,1.749918e+09,result_mmbf_22686000_100_selected.csv,100

In [7]:
df["preprocessing_time"] = pd.to_numeric(df["preprocessing_time"], errors="coerce")
df[["block_number", "algorithm_name", "top_coins", "preprocessing_time", "algorithm_execution_time"]].groupby(["algorithm_name", "top_coins"]).agg({
        "preprocessing_time": ["mean", "min", "max"],
        "algorithm_execution_time": ["mean", "min", "max"]
    }).round(5)

                         preprocessing_time                    \
                                       mean      min      max
algorithm_name top_coins
mmbf           100                  0.00000  0.00000  0.00001
               200                  0.00000  0.00000  0.00001
               300                  0.00000  0.00000  0.00002
               400                  0.00000  0.00000  0.00001
               500                  0.00000  0.00000  0.00001
ours           100                  0.00909  0.00249  0.15609
               200                  0.02193  0.00458  0.20562
               300                  0.04006  0.00653  0.26419
               400                  0.06641  0.01358  0.29227
               500                  0.09082  0.01219  0.38754
               600                  0.12081  0.01519  0.40043
               700                  0.25013  0.02648  0.63795
               800                  0.28660  0.02811  0.77156
               900                  0.31600  0.02699  0.91039
               1000                 0.35984  0.04934  0.94387

                         algorithm_execution_time
                                             mean       min           max
algorithm_name top_coins
mmbf           100                   2.498379e+07   0.01496  1.749918e+09
               200                   1.678850e+00   0.07890  2.853880e+00
               300                   5.058330e+00   0.24806  7.592990e+00
               400                   9.866420e+00   0.37325  1.000721e+01
               500                   1.000000e+01  10.00000  1.000000e+01
ours           100                   3.800000e-04   0.00006  9.976000e-02
               200                   1.320000e-03   0.00014  9.865000e-02
               300                   2.990000e-03   0.00025  9.904000e-02
               400                   5.150000e-03   0.00054  9.958000e-02
               500                   7.740000e-03   0.00040  1.004600e-01
               600                   1.076000e-02   0.00072  2.835100e-01
               700                   1.434000e-02   0.00130  1.867200e-01
               800                   1.783000e-02   0.00112  2.092800e-01
               900                   2.195000e-02   0.00130  2.001900e-01
               1000                  2.660000e-02   0.00187  2.336100e-01